export interface NavItemConfig {
    label: string;
    icon: string;
    route?: string;
    /** External URL for standalone apps (used instead of route when set) */
    url?: string;
    match: string;
    permission: string;
    section: string;
    keywords?: string[];
    /** Opens in a separate browser tab (e.g. standalone POS app) */
    opensInNewTab?: boolean;
    /** Hidden in sidebar and command palette when session scope is store. */
    companyScopeOnly?: boolean;
}

export const navSections = [
    { id: 'overview', label: 'Overview' },
    { id: 'organization', label: 'Organization' },
    { id: 'catalog', label: 'Catalog' },
    { id: 'inventory', label: 'Inventory' },
    { id: 'purchasing', label: 'Purchasing' },
    { id: 'crm', label: 'CRM' },
    { id: 'online-store', label: 'Online Store' },
    { id: 'reports', label: 'Reports' },
    { id: 'accounting', label: 'Accounting' },
    { id: 'access', label: 'Access' },
    { id: 'system', label: 'System' },
] as const;

export const navItems: NavItemConfig[] = [
    {
        label: 'Dashboard',
        icon: 'dashboard',
        route: 'dashboard',
        match: 'dashboard',
        permission: 'dashboard.view',
        section: 'overview',
        keywords: ['home', 'overview', 'analytics', 'summary'],
    },
    {
        label: 'POS',
        icon: 'pos-terminal',
        url: '__POS_APP_URL__',
        match: 'pos.*',
        permission: 'pos.access',
        section: 'overview',
        keywords: ['pos', 'terminal', 'cashier', 'checkout', 'register'],
        opensInNewTab: true,
    },
    {
        label: 'Kitchen Display',
        icon: 'kitchen',
        route: 'kds.index',
        match: 'kds.*',
        permission: 'kds.view',
        section: 'overview',
        keywords: ['kds', 'kitchen', 'display', 'orders', 'prep', 'restaurant'],
    },
    {
        label: 'Companies',
        icon: 'companies',
        route: 'admin.companies.index',
        match: 'admin.companies.*',
        permission: 'companies.view',
        section: 'organization',
        companyScopeOnly: true,
        keywords: ['company', 'tenant', 'business', 'organization'],
    },
    {
        label: 'Stores',
        icon: 'stores',
        route: 'admin.stores.index',
        match: 'admin.stores.*',
        permission: 'stores.view',
        section: 'organization',
        keywords: ['store', 'branch', 'location', 'outlet', 'shop'],
    },
    {
        label: 'Sales Plan',
        icon: 'sales-plans',
        route: 'admin.sales-plans.index',
        match: 'admin.sales-plans.*',
        permission: 'sales_plans.view',
        section: 'organization',
        keywords: ['sales plan', 'catalog', 'retail', 'restaurant', 'store group', 'product group'],
    },
    {
        label: 'Registers',
        icon: 'registers',
        route: 'admin.registers.index',
        match: 'admin.registers.*',
        permission: 'registers.view',
        section: 'organization',
        keywords: ['register', 'pos', 'terminal', 'cashier', 'device'],
    },
    {
        label: 'Products',
        icon: 'products',
        route: 'admin.products.index',
        match: 'admin.products.*',
        permission: 'products.view',
        section: 'catalog',
        keywords: ['product', 'item', 'sku', 'catalog', 'merchandise'],
    },
    {
        label: 'Categories',
        icon: 'categories',
        route: 'admin.categories.index',
        match: 'admin.categories.*',
        permission: 'categories.view',
        section: 'catalog',
        keywords: ['category', 'group', 'department', 'classification'],
    },
    {
        label: 'Brands',
        icon: 'brands',
        route: 'admin.brands.index',
        match: 'admin.brands.*',
        permission: 'brands.view',
        section: 'catalog',
        keywords: ['brand', 'manufacturer', 'vendor'],
    },
    {
        label: 'Units',
        icon: 'units',
        route: 'admin.units.index',
        match: 'admin.units.*',
        permission: 'units.view',
        section: 'catalog',
        keywords: ['unit', 'uom', 'measure', 'piece', 'kg'],
    },
    {
        label: 'Taxes',
        icon: 'taxes',
        route: 'admin.taxes.index',
        match: 'admin.taxes.*',
        permission: 'taxes.view',
        section: 'catalog',
        keywords: ['tax', 'vat', 'rate', 'inclusive'],
    },
    {
        label: 'Price Groups',
        icon: 'price-groups',
        route: 'admin.price-groups.index',
        match: 'admin.price-groups.*',
        permission: 'price_groups.view',
        section: 'catalog',
        keywords: ['price', 'group', 'tier', 'retail', 'wholesale'],
    },
    {
        label: 'Store Stock',
        icon: 'warehouse',
        route: 'admin.inventory.stock.index',
        match: 'admin.inventory.stock.*',
        permission: 'inventory.view',
        section: 'inventory',
        keywords: ['inventory', 'stock', 'on hand', 'balance', 'store stock'],
    },
    {
        label: 'Stock Movements',
        icon: 'movements',
        route: 'admin.inventory.movements.index',
        match: 'admin.inventory.movements.*',
        permission: 'inventory.view',
        section: 'inventory',
        keywords: ['inventory', 'movement', 'ledger', 'history', 'adjustment', 'sale'],
    },
    {
        label: 'Adjust Stock',
        icon: 'adjust',
        route: 'admin.inventory.adjustments.create',
        match: 'admin.inventory.adjustments.*',
        permission: 'inventory.adjust',
        section: 'inventory',
        keywords: ['inventory', 'adjust', 'correction', 'stock count', 'add', 'remove'],
    },
    {
        label: 'Stock Transfers',
        icon: 'transfer',
        route: 'admin.inventory.transfers.index',
        match: 'admin.inventory.transfers.*',
        permission: 'inventory.view',
        section: 'inventory',
        keywords: ['inventory', 'transfer', 'inter-store', 'move stock', 'branch'],
    },
    {
        label: 'Low Stock Alerts',
        icon: 'low-stock',
        route: 'admin.inventory.low-stock',
        match: 'admin.inventory.low-stock',
        permission: 'inventory.view',
        section: 'inventory',
        keywords: ['inventory', 'stock', 'low stock', 'warning', 'qty', 'alert', 'restock'],
    },
    {
        label: 'Suppliers',
        icon: 'truck',
        route: 'admin.suppliers.index',
        match: 'admin.suppliers.*',
        permission: 'purchasing.view',
        section: 'purchasing',
        keywords: ['supplier', 'vendor', 'purchasing'],
    },
    {
        label: 'Purchase Orders',
        icon: 'purchase-order',
        route: 'admin.purchase-orders.index',
        match: 'admin.purchase-orders.*',
        permission: 'purchasing.view',
        section: 'purchasing',
        keywords: ['purchase', 'order', 'po', 'receiving', 'receipt'],
    },
    {
        label: 'Purchase Returns',
        icon: 'purchase-return',
        route: 'admin.purchase-returns.index',
        match: 'admin.purchase-returns.*',
        permission: 'purchasing.view',
        section: 'purchasing',
        keywords: ['return', 'supplier', 'purchase return'],
    },
    {
        label: 'Customers',
        icon: 'customers',
        route: 'admin.customers.index',
        match: 'admin.customers.*',
        permission: 'customers.view',
        section: 'crm',
        keywords: ['customer', 'crm', 'client', 'buyer'],
    },
    {
        label: 'Loyalty Programs',
        icon: 'gift',
        route: 'admin.loyalty-programs.index',
        match: 'admin.loyalty-programs.*',
        permission: 'loyalty.view',
        section: 'crm',
        keywords: ['loyalty', 'points', 'rewards'],
    },
    {
        label: 'Membership Plans',
        icon: 'membership',
        route: 'admin.membership-plans.index',
        match: 'admin.membership-plans.*',
        permission: 'memberships.view',
        section: 'crm',
        keywords: ['membership', 'member', 'subscription'],
    },
    {
        label: 'Promotions',
        icon: 'megaphone',
        route: 'admin.promotions.index',
        match: 'admin.promotions.*',
        permission: 'promotions.view',
        section: 'crm',
        keywords: ['promotion', 'discount', 'promo', 'sale'],
    },
    {
        label: 'Online Store Settings',
        icon: 'globe',
        route: 'admin.online-store-settings.index',
        match: 'admin.online-store-settings.*',
        permission: 'online_store.view',
        section: 'online-store',
        keywords: ['online', 'storefront', 'ecommerce', 'web store', 'slug', 'publish'],
    },
    {
        label: 'Online Orders',
        icon: 'stores',
        route: 'admin.online-orders.index',
        match: 'admin.online-orders.*',
        permission: 'online_store.view',
        section: 'online-store',
        keywords: ['online', 'orders', 'delivery', 'pickup', 'storefront'],
    },
    {
        label: 'Sales Summary',
        icon: 'chart-bar',
        route: 'admin.reports.sales-summary.index',
        match: 'admin.reports.sales-summary.*',
        permission: 'reports.view',
        section: 'reports',
        keywords: ['report', 'sales', 'summary', 'kpi', 'analytics'],
    },
    {
        label: 'Sales Register',
        icon: 'receipt',
        route: 'admin.reports.sales-register.index',
        match: 'admin.reports.sales-register.*',
        permission: 'reports.view',
        section: 'reports',
        keywords: ['report', 'sales', 'register', 'transactions', 'export'],
    },
    {
        label: 'Product Sales',
        icon: 'chart-pie',
        route: 'admin.reports.product-sales.index',
        match: 'admin.reports.product-sales.*',
        permission: 'reports.view',
        section: 'reports',
        keywords: ['report', 'product', 'top sellers', 'revenue'],
    },
    {
        label: 'Shift Reports',
        icon: 'clock',
        route: 'admin.reports.shift-reports.index',
        match: 'admin.reports.shift-reports.*',
        permission: 'reports.view',
        section: 'reports',
        keywords: ['report', 'shift', 'z-report', 'cash', 'drawer', 'register', 'reconciliation'],
    },
    {
        label: 'Chart of Accounts',
        icon: 'book-open',
        route: 'admin.chart-of-accounts.index',
        match: 'admin.chart-of-accounts.*',
        permission: 'accounting.view',
        section: 'accounting',
        keywords: ['accounting', 'gl', 'chart', 'ledger', 'coa'],
    },
    {
        label: 'Journal Entries',
        icon: 'journal',
        route: 'admin.journal-entries.index',
        match: 'admin.journal-entries.*',
        permission: 'accounting.view',
        section: 'accounting',
        keywords: ['accounting', 'journal', 'entry', 'posting', 'gl'],
    },
    {
        label: 'Trial Balance',
        icon: 'scale',
        route: 'admin.accounting.trial-balance.index',
        match: 'admin.accounting.trial-balance.*',
        permission: 'accounting.view',
        section: 'accounting',
        keywords: ['accounting', 'trial balance', 'gl', 'report'],
    },
    {
        label: 'Profit & Loss',
        icon: 'trending-up',
        route: 'admin.accounting.profit-and-loss.index',
        match: 'admin.accounting.profit-and-loss.*',
        permission: 'accounting.view',
        section: 'accounting',
        keywords: ['accounting', 'profit', 'loss', 'income statement', 'p&l'],
    },
    {
        label: 'Balance Sheet',
        icon: 'table-cells',
        route: 'admin.accounting.balance-sheet.index',
        match: 'admin.accounting.balance-sheet.*',
        permission: 'accounting.view',
        section: 'accounting',
        keywords: ['accounting', 'balance sheet', 'assets', 'liabilities', 'equity'],
    },
    {
        label: 'Vendor Bills',
        icon: 'invoice',
        route: 'admin.vendor-bills.index',
        match: 'admin.vendor-bills.*',
        permission: 'ap.view',
        section: 'accounting',
        keywords: ['accounts payable', 'vendor bill', 'ap', 'supplier invoice'],
    },
    {
        label: 'Supplier Payments',
        icon: 'banknotes',
        route: 'admin.supplier-payments.index',
        match: 'admin.supplier-payments.*',
        permission: 'ap.view',
        section: 'accounting',
        keywords: ['accounts payable', 'supplier payment', 'ap', 'pay bill'],
    },
    {
        label: 'AP Aging',
        icon: 'calendar',
        route: 'admin.accounting.ap-aging.index',
        match: 'admin.accounting.ap-aging.*',
        permission: 'ap.view',
        section: 'accounting',
        keywords: ['accounts payable', 'aging', 'ap', 'outstanding'],
    },
    {
        label: 'Users',
        icon: 'team',
        route: 'admin.users.index',
        match: 'admin.users.*',
        permission: 'users.view',
        section: 'access',
        keywords: ['user', 'staff', 'employee', 'account', 'team'],
    },
    {
        label: 'Roles',
        icon: 'roles',
        route: 'admin.roles.index',
        match: 'admin.roles.*',
        permission: 'roles.view',
        section: 'access',
        companyScopeOnly: true,
        keywords: ['role', 'permission', 'access', 'security'],
    },
    {
        label: 'POS Devices',
        icon: 'device',
        route: 'admin.pos-devices.index',
        match: 'admin.pos-devices.*',
        permission: 'sync.manage',
        section: 'system',
        companyScopeOnly: true,
        keywords: ['device', 'sync', 'offline', 'terminal', 'pos device'],
    },
    {
        label: 'POS UI',
        icon: 'paint-brush',
        route: 'admin.pos-ui.edit',
        match: 'admin.pos-ui.*',
        permission: 'settings.view',
        section: 'system',
        companyScopeOnly: true,
        keywords: ['pos', 'ui', 'terminal', 'layout', 'retail', 'restaurant', 'interface', 'customization'],
    },
    {
        label: 'Settings',
        icon: 'settings',
        route: 'admin.settings.edit',
        match: 'admin.settings.*',
        permission: 'settings.view',
        section: 'system',
        companyScopeOnly: true,
        keywords: ['setting', 'config', 'configuration', 'preferences'],
    },
    {
        label: 'Audit Logs',
        icon: 'audit',
        route: 'admin.audit-logs.index',
        match: 'admin.audit-logs.*',
        permission: 'audit.view',
        section: 'system',
        keywords: ['audit', 'log', 'history', 'activity', 'trail'],
    },
];

export const utilityNavItems: NavItemConfig[] = [
    {
        label: 'Appearance',
        icon: 'appearance',
        route: 'appearance.edit',
        match: 'appearance.*',
        permission: '',
        section: 'utility',
        keywords: ['theme', 'color', 'layout', 'sidebar', 'topbar', 'accent'],
    },
    {
        label: 'Profile',
        icon: 'profile',
        route: 'profile.edit',
        match: 'profile.*',
        permission: '',
        section: 'utility',
        keywords: ['profile', 'account', 'password', 'email'],
    },
];
