<?php

namespace Ispos\Backoffice\Http\Requests\Admin\Concerns;

use App\Domains\Catalog\Services\ProductImageService;
use Illuminate\Validation\Rule;

trait ValidatesProductFields
{
    protected function productRules(?string $productId = null, ?string $companyId = null): array
    {
        return [
            'company_id' => ['required', 'ulid', 'exists:companies,id'],
            'sales_plan_id' => [
                'required',
                'ulid',
                Rule::exists('sales_plans', 'id')->where(fn ($q) => $q->where('company_id', $companyId)),
            ],
            'sku' => [
                'required', 'string', 'max:100',
                Rule::unique('products', 'sku')->where(fn ($q) => $q->where('company_id', $companyId))->ignore($productId),
            ],
            'name' => ['required', 'string', 'max:255'],
            'description' => ['nullable', 'string'],
            'product_type' => ['required', Rule::in(['retail', 'menu_item', 'ingredient'])],
            'category_id' => ['nullable', 'ulid', 'exists:categories,id'],
            'brand_id' => ['nullable', 'ulid', 'exists:brands,id'],
            'unit_id' => ['nullable', 'ulid', 'exists:units,id'],
            'tax_id' => ['nullable', 'ulid', 'exists:taxes,id'],
            'cost' => ['nullable', 'numeric', 'min:0'],
            'base_price' => ['nullable', 'numeric', 'min:0'],
            'track_inventory' => ['boolean'],
            'qty' => ['nullable', 'numeric', 'min:0'],
            'ideal_qty' => ['nullable', 'numeric', 'min:0'],
            'warning_qty' => ['nullable', 'numeric', 'min:0'],
            'has_variants' => ['boolean'],
            'has_modifiers' => ['boolean'],
            'has_components' => ['boolean'],
            'image' => ['nullable', 'string', 'max:500'],
            'image_uploads' => ['nullable', 'array', 'max:'.ProductImageService::MAX_IMAGES_PER_PRODUCT],
            'image_uploads.*' => [
                'file',
                'image',
                'mimes:jpeg,jpg,png,webp,gif',
                'max:'.ProductImageService::MAX_UPLOAD_KILOBYTES,
            ],
            'images' => ['nullable', 'array', 'max:'.ProductImageService::MAX_IMAGES_PER_PRODUCT],
            'images.*.id' => ['nullable', 'ulid', 'exists:product_images,id'],
            'images.*.client_key' => ['nullable', 'string', 'max:100'],
            'images.*.upload_index' => ['nullable', 'integer', 'min:0'],
            'images.*.is_default' => ['boolean'],
            'images.*.sort_order' => ['nullable', 'integer', 'min:0'],
            'status' => ['required', Rule::in(['active', 'inactive'])],
            'variants' => ['nullable', 'array'],
            'variants.*.id' => ['nullable', 'ulid', 'exists:product_variants,id'],
            'variants.*.client_key' => ['nullable', 'string', 'max:100'],
            'variants.*.variant_code' => ['required_with:variants', 'string', 'max:50'],
            'variants.*.name' => ['required_with:variants', 'string', 'max:255'],
            'variants.*.sku' => ['nullable', 'string', 'max:100'],
            'variants.*.cost' => ['nullable', 'numeric', 'min:0'],
            'variants.*.selling_price' => ['nullable', 'numeric', 'min:0'],
            'variants.*.sort_order' => ['nullable', 'integer', 'min:0'],
            'variants.*.status' => ['nullable', Rule::in(['active', 'inactive'])],
            'barcodes' => ['nullable', 'array'],
            'barcodes.*.id' => ['nullable', 'ulid', 'exists:product_barcodes,id'],
            'barcodes.*.barcode' => ['required_with:barcodes', 'string', 'max:100'],
            'barcodes.*.is_primary' => ['boolean'],
            'barcodes.*.product_variant_id' => ['nullable', 'ulid', 'exists:product_variants,id'],
            'barcodes.*.variant_client_key' => ['nullable', 'string', 'max:100'],
            'prices' => ['nullable', 'array'],
            'prices.*.price_group_id' => ['required_with:prices', 'ulid', 'exists:price_groups,id'],
            'prices.*.price' => ['nullable', 'numeric', 'min:0'],
            'prices.*.product_variant_id' => ['nullable', 'ulid', 'exists:product_variants,id'],
            'prices.*.variant_client_key' => ['nullable', 'string', 'max:100'],
            'modifier_groups' => ['nullable', 'array'],
            'modifier_groups.*.id' => ['nullable', 'ulid', 'exists:product_modifier_groups,id'],
            'modifier_groups.*.client_key' => ['nullable', 'string', 'max:100'],
            'modifier_groups.*.group_code' => ['required_with:modifier_groups', 'string', 'max:50'],
            'modifier_groups.*.name' => ['required_with:modifier_groups', 'string', 'max:255'],
            'modifier_groups.*.selection_type' => ['nullable', Rule::in(['single', 'multiple'])],
            'modifier_groups.*.is_required' => ['boolean'],
            'modifier_groups.*.min_selections' => ['nullable', 'integer', 'min:0'],
            'modifier_groups.*.max_selections' => ['nullable', 'integer', 'min:1'],
            'modifier_groups.*.sort_order' => ['nullable', 'integer', 'min:0'],
            'modifier_groups.*.status' => ['nullable', Rule::in(['active', 'inactive'])],
            'modifier_groups.*.options' => ['nullable', 'array'],
            'modifier_groups.*.options.*.id' => ['nullable', 'ulid', 'exists:product_modifier_options,id'],
            'modifier_groups.*.options.*.client_key' => ['nullable', 'string', 'max:100'],
            'modifier_groups.*.options.*.option_code' => ['required_with:modifier_groups.*.options', 'string', 'max:50'],
            'modifier_groups.*.options.*.name' => ['required_with:modifier_groups.*.options', 'string', 'max:255'],
            'modifier_groups.*.options.*.price_adjustment' => ['nullable', 'numeric'],
            'modifier_groups.*.options.*.is_default' => ['boolean'],
            'modifier_groups.*.options.*.sort_order' => ['nullable', 'integer', 'min:0'],
            'modifier_groups.*.options.*.status' => ['nullable', Rule::in(['active', 'inactive'])],
            'components' => ['nullable', 'array'],
            'components.*.id' => ['nullable', 'ulid', 'exists:product_components,id'],
            'components.*.component_product_id' => ['required_with:components', 'ulid', 'exists:products,id'],
            'components.*.quantity' => ['nullable', 'numeric', 'min:0.0001'],
            'components.*.unit_id' => ['nullable', 'ulid', 'exists:units,id'],
            'components.*.is_optional' => ['boolean'],
            'components.*.sort_order' => ['nullable', 'integer', 'min:0'],
            'components.*.notes' => ['nullable', 'string', 'max:500'],
            'ingredients' => ['nullable', 'array'],
            'ingredients.*.id' => ['nullable', 'ulid', 'exists:product_ingredients,id'],
            'ingredients.*.ingredient_product_id' => ['required_with:ingredients', 'ulid', 'exists:products,id'],
            'ingredients.*.quantity' => ['nullable', 'numeric', 'min:0.0001'],
            'ingredients.*.unit_id' => ['nullable', 'ulid', 'exists:units,id'],
            'ingredients.*.is_optional' => ['boolean'],
            'ingredients.*.sort_order' => ['nullable', 'integer', 'min:0'],
            'ingredients.*.notes' => ['nullable', 'string', 'max:500'],
        ];
    }

    /** @return array<string, mixed> */
    protected function bulkProductRules(?string $companyId = null): array
    {
        return [
            'company_id' => ['required', 'ulid', 'exists:companies,id'],
            'sales_plan_id' => [
                'required',
                'ulid',
                Rule::exists('sales_plans', 'id')->where(fn ($q) => $q->where('company_id', $companyId)),
            ],
            'product_type' => ['required', Rule::in(['retail', 'menu_item', 'ingredient'])],
            'tax_id' => [
                'nullable',
                'ulid',
                Rule::exists('taxes', 'id')->where(fn ($q) => $q->where('company_id', $companyId)),
            ],
            'track_inventory' => ['boolean'],
            'status' => ['required', Rule::in(['active', 'inactive'])],
            'items' => ['required', 'array', 'min:1'],
            'items.*.sku' => [
                'required',
                'string',
                'max:100',
                'distinct',
                Rule::unique('products', 'sku')->where(fn ($q) => $q->where('company_id', $companyId)),
            ],
            'items.*.name' => ['required', 'string', 'max:255'],
            'items.*.description' => ['nullable', 'string'],
            'items.*.cost' => ['nullable', 'numeric', 'min:0'],
            'items.*.base_price' => ['nullable', 'numeric', 'min:0'],
            'items.*.barcode' => [
                'nullable',
                'string',
                'max:100',
                Rule::unique('product_barcodes', 'barcode')->where(fn ($q) => $q->where('company_id', $companyId)),
            ],
            'items.*.ideal_qty' => ['nullable', 'numeric', 'min:0'],
            'items.*.warning_qty' => ['nullable', 'numeric', 'min:0'],
            'items.*.category_id' => [
                'nullable',
                'ulid',
                Rule::exists('categories', 'id')->where(fn ($q) => $q->where('company_id', $companyId)),
            ],
            'items.*.brand_id' => [
                'nullable',
                'ulid',
                Rule::exists('brands', 'id')->where(fn ($q) => $q->where('company_id', $companyId)),
            ],
            'items.*.unit_id' => [
                'nullable',
                'ulid',
                Rule::exists('units', 'id')->where(fn ($q) => $q->where('company_id', $companyId)),
            ],
            'items.*.has_variants' => ['boolean'],
            'items.*.has_modifiers' => ['boolean'],
            'items.*.has_components' => ['boolean'],
            'items.*.variants' => ['nullable', 'array'],
            'items.*.variants.*.client_key' => ['required', 'string', 'max:100'],
            'items.*.variants.*.variant_code' => ['required_with:items.*.variants', 'string', 'max:50'],
            'items.*.variants.*.name' => ['required_with:items.*.variants', 'string', 'max:255'],
            'items.*.variants.*.sku' => ['nullable', 'string', 'max:100'],
            'items.*.variants.*.cost' => ['nullable', 'numeric', 'min:0'],
            'items.*.variants.*.selling_price' => ['nullable', 'numeric', 'min:0'],
            'items.*.variants.*.sort_order' => ['nullable', 'integer', 'min:0'],
            'items.*.variants.*.status' => ['nullable', Rule::in(['active', 'inactive'])],
            'items.*.modifier_groups' => ['nullable', 'array'],
            'items.*.modifier_groups.*.client_key' => ['required', 'string', 'max:100'],
            'items.*.modifier_groups.*.group_code' => ['required', 'string', 'max:50'],
            'items.*.modifier_groups.*.name' => ['required', 'string', 'max:255'],
            'items.*.modifier_groups.*.selection_type' => ['nullable', Rule::in(['single', 'multiple'])],
            'items.*.modifier_groups.*.is_required' => ['boolean'],
            'items.*.modifier_groups.*.min_selections' => ['nullable', 'integer', 'min:0'],
            'items.*.modifier_groups.*.max_selections' => ['nullable', 'integer', 'min:1'],
            'items.*.modifier_groups.*.sort_order' => ['nullable', 'integer', 'min:0'],
            'items.*.modifier_groups.*.status' => ['nullable', Rule::in(['active', 'inactive'])],
            'items.*.modifier_groups.*.options' => ['nullable', 'array'],
            'items.*.modifier_groups.*.options.*.client_key' => ['required', 'string', 'max:100'],
            'items.*.modifier_groups.*.options.*.option_code' => ['required', 'string', 'max:50'],
            'items.*.modifier_groups.*.options.*.name' => ['required', 'string', 'max:255'],
            'items.*.modifier_groups.*.options.*.price_adjustment' => ['nullable', 'numeric'],
            'items.*.modifier_groups.*.options.*.is_default' => ['boolean'],
            'items.*.modifier_groups.*.options.*.sort_order' => ['nullable', 'integer', 'min:0'],
            'items.*.modifier_groups.*.options.*.status' => ['nullable', Rule::in(['active', 'inactive'])],
            'items.*.components' => ['nullable', 'array'],
            'items.*.components.*.component_product_id' => [
                'required',
                'ulid',
                Rule::exists('products', 'id')->where(fn ($q) => $q
                    ->where('company_id', $companyId)
                    ->whereIn('product_type', ['retail', 'menu_item'])
                    ->where('status', 'active')
                    ->whereNull('deleted_at')),
            ],
            'items.*.components.*.quantity' => ['nullable', 'numeric', 'min:0.0001'],
            'items.*.components.*.unit_id' => [
                'nullable',
                'ulid',
                Rule::exists('units', 'id')->where(fn ($q) => $q->where('company_id', $companyId)),
            ],
            'items.*.components.*.is_optional' => ['boolean'],
            'items.*.components.*.sort_order' => ['nullable', 'integer', 'min:0'],
            'items.*.components.*.notes' => ['nullable', 'string', 'max:500'],
            'items.*.ingredients' => ['nullable', 'array'],
            'items.*.ingredients.*.ingredient_product_id' => [
                'required',
                'ulid',
                Rule::exists('products', 'id')->where(fn ($q) => $q
                    ->where('company_id', $companyId)
                    ->where('product_type', 'ingredient')
                    ->where('status', 'active')
                    ->whereNull('deleted_at')),
            ],
            'items.*.ingredients.*.quantity' => ['nullable', 'numeric', 'min:0.0001'],
            'items.*.ingredients.*.unit_id' => [
                'nullable',
                'ulid',
                Rule::exists('units', 'id')->where(fn ($q) => $q->where('company_id', $companyId)),
            ],
            'items.*.ingredients.*.is_optional' => ['boolean'],
            'items.*.ingredients.*.sort_order' => ['nullable', 'integer', 'min:0'],
            'items.*.ingredients.*.notes' => ['nullable', 'string', 'max:500'],
            'items.*.image_uploads' => ['nullable', 'array', 'max:'.ProductImageService::MAX_IMAGES_PER_PRODUCT],
            'items.*.image_uploads.*' => [
                'file',
                'image',
                'mimes:jpeg,jpg,png,webp,gif',
                'max:'.ProductImageService::MAX_UPLOAD_KILOBYTES,
            ],
            'items.*.images' => ['nullable', 'array', 'max:'.ProductImageService::MAX_IMAGES_PER_PRODUCT],
            'items.*.images.*.client_key' => ['nullable', 'string', 'max:100'],
            'items.*.images.*.upload_index' => ['required', 'integer', 'min:0'],
            'items.*.images.*.is_default' => ['boolean'],
            'items.*.images.*.sort_order' => ['nullable', 'integer', 'min:0'],
        ];
    }
}
